# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from ui import my_widgets
from ui.my_widgets import *

class A_form(QtWidgets.QWidget):
    def __init__(self, Form, event):
        QtWidgets.QWidget.__init__(self)
        Form.setObjectName("MainWindow")
        Form.resize(800, 600)
        Form.setStyleSheet('QMainWindow {background-color: #242424; color: #E6E6E6;}')
        self.pushButton = my_btn(Form)
        self.pushButton.setGeometry(QtCore.QRect(360, 310, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = my_line_edit(Form)
        self.textEdit.setGeometry(QtCore.QRect(170, 150, 104, 71))
        self.textEdit.setObjectName("textEdit")
        self.label = my_label(Form)
        self.label.setGeometry(QtCore.QRect(150, 330, 131, 81))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        self.event_connect(event)

        QtCore.QMetaObject.connectSlotsByName(Form)

    def event_connect(self, event):
        self.pushButton.clicked.connect(event.btnClike)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
